name: wealth_orbit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_riverpod: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_auth: ^6.1.4
  firebase_core: any
  google_sign_in: ^6.2.1
  fl_chart: any
  tflite_flutter: any
  intl: any
  path_provider: any
  equatable: any
  fpdart: any

dependency_overrides:
  isar_flutter_libs:
    path: vendor/isar_flutter_libs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  isar_generator: any

flutter:
  uses-material-design: true
