name: wealth_orbit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6
  fl_chart: ^0.66.0
  intl: ^0.19.0
  path_provider: ^2.1.2
  equatable: ^2.0.5
  fpdart: ^1.1.0
  # For Schema Analysis
  spreadsheet_decoder: ^2.1.1

dependency_overrides:
  isar_flutter_libs:
    path: vendor/isar_flutter_libs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
